name: Deploy to one.com

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug info
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in the directory:"
        ls -la
        echo "Hello World!"